### ISSUE TITLE
Kernel panic file

### ISSUE THREAD

**Issue by DamieFC** [MandelbrotOS/MandelbrotOS#23]
Hello! First, I just want to say this is really neat. I was looking and I didn't find a kernel panic file or function. I wanted to suggest adding one (I would do it but I'm not sure exactly how to do it).

**Comment by CaydendW** [comment]
I would need to write us some IRQs and ISRs. We had those in the 32 bit version. I probably should base the design around some of our old work. I have though about doing the BSOD but I am wrapped up in all kinds of other things. The IDT is complete just need to do the handelers. If you could help that would also be much appriciated.

**Comment by DamieFC** [comment]
Ok. I'll read more of the code so I know what the heck I'm doing, then I'll embark on that adventure 😀.

**Comment by DamieFC** [comment]
After reading more of the code, I realized: I can't find where the shell is located! I know it's here somewhere, and I know when I find out I'm gonna feel stupid, but _where the heck is it?_ Sorry if this sounds rude.

**Comment by timas130** [comment]
> After reading more of the code, I realized: I can't find where the shell is located! I know it's here somewhere, and I know when I find out I'm gonna feel stupid, but _where the heck is it?_ Sorry if this sounds rude.

Actually, after #19 the shell was completely cut out from the kernel, though the README remained the same.

**Comment by DamieFC** [comment]
Ooh. Interesting.

**Comment by CaydendW** [comment]
A complete rewrite of the kernel happened. Hence the shell was removed.

**Comment by DamieFC** [comment]
Ah, I see.

**Comment by CaydendW** [comment]
ISRs have been written. Kernel panic file coming soon to a hobby OS near you

**Comment by DamieFC** [comment]
yay!

**Comment by DamieFC** [comment]
Huh, it actually looks like there was a kernel panic file (`kpanic.c`) before the same rewrite that deleted the CLI (`Total rewrite`?).
![The commit message, Total rewrite](https://user-images.githubusercontent.com/69485115/115128184-cf7b3f80-9f90-11eb-9d94-fb6377b0d896.png)
![The possible kernel panic file?](https://user-images.githubusercontent.com/69485115/115128182-ce4a1280-9f90-11eb-84fa-2e694ffefe12.png)

**Comment by Abb1x** [comment]
Mayb I could work on that

**Comment by Abb1x** [comment]
> Huh, it actually looks like there was a kernel panic file (`kpanic.c`) before the same rewrite that deleted the CLI (`Total rewrite`?).
> ![The commit message, Total rewrite](https://user-images.githubusercontent.com/69485115/115128184-cf7b3f80-9f90-11eb-9d94-fb6377b0d896.png)
> ![The possible kernel panic file?](https://user-images.githubusercontent.com/69485115/115128182-ce4a1280-9f90-11eb-84fa-2e694ffefe12.png)
> 

Yeah no that file was not good at all (iirc)

**Comment by DamieFC** [comment]
Oh ok.

**Comment by DamieFC** [comment]
Looks like this is being worked on in #43 so I'll close this.

**Comment by DamieFC** [comment]
I think I can do a simple panic thing, but if I were to, where might I put it?

**Comment by DamieFC** [comment]
Also sorry for reopening and closing and reopening

**Comment by CaydendW** [comment]
Rewrite happened. Issue closed
