### ISSUE TITLE
LAI fails to initialize

### ISSUE THREAD

**Issue by A52-bit** [MandelbrotOS/MandelbrotOS#42]
For some reason, LAI is not working. (I am running qemu from the makefile)

![image](https://user-images.githubusercontent.com/63597349/117541155-e8539f80-afe8-11eb-93fd-2b367bd087ee.png)

**Comment by CaydendW** [comment]
I am so sorry but I am getting this too. I am trying to fix it but I am having troubles. Keep the issue open but I think it has to do with the compiler/compile options.

**Comment by AtieP** [comment]
It only works in my machine :^)
Jokes aside it works on my computer

**Comment by AtieP** [comment]
Also the bss is fucked

**Comment by CaydendW** [comment]
I

> Also the bss is fucked

Is it on your too?

**Comment by A52-bit** [comment]
@CaydendW I passed -acpitable to qemu and got a different error:
![image](https://user-images.githubusercontent.com/63597349/117541333-c9094200-afe9-11eb-93a9-d0d0bf5a94a9.png)

@AtieP Did you test on a real machine? Maybe qemu options are messed up

**Comment by AtieP** [comment]
Compiling it in my machine and running it in my qemu works just fine, also what is your discord id?

**Comment by AtieP** [comment]
> I
> 
> > Also the bss is fucked
> 
> Is it on your too?

No, it is just bogus, it is not normal to realloc 0x123456 bytes

**Comment by A52-bit** [comment]
@AtieP What are your compiler options? Here is my (modified) makefile:

```ASFLAGS = -f elf64

CFLAGS := \
	-mcmodel=kernel \
	-ffreestanding \
	-fno-pie \
	-fno-pic \
	-O2 \
	-s \
	-Isrc/include \
	-Wall \
	-Wextra \
	-lm \
	-std=gnu99 \
	-fcommon \
	-Isrc/acpi/lai/include \
	-Isrc/include

LDFLAGS := \
	-static \
	-no-pie \
	-no-pic \
	-Tresources/linker.ld \
	-L.\
	-lgcc \
	-nostdlib
```

I have discord, but I lost my password, and I am too lazy to recover

**Comment by CaydendW** [comment]
Rewrite happened. Issue closed
