### ISSUE TITLE
Toolchain build error

### ISSUE THREAD

**Issue by aa2006** [MandelbrotOS/MandelbrotOS#44]
Running ```./scripts/build-tools.sh``` results in the following error:

```bash
2021-05-12 15:39:11 URL: ftp://gcc.gnu.org/pub/gcc/infrastructure/mpfr-3.1.4.tar.bz2 [1279284] -> "./mpfr-3.1.4.tar.bz2" [1]
error: Cannot download mpc-1.0.3.tar.gz from ftp://gcc.gnu.org/pub/gcc/infrastructure/

Previous command failed with exit code 1; quitting...
```

**Comment by notbluu** [comment]
Try using wget to get that file manually.

**Comment by unsafecast** [comment]
@aa2006 just did a fresh clone of Mandelbrot and I don't have this error. I'd need some more information:

- Do you have `wget` + all the GCC dependencies? ([this page](https://wiki.osdev.org/GCC_Cross-Compiler) lists them nicely)
- What OS are you using?
- Did you clone recursively? (`git clone --recursive https://github.com/MandelbrotOS/MandelbrotOS.git`)

**Comment by aa2006** [comment]
I didnt clone recursively, ill try that now. I have the dependencies, and I'm using Manjaro Linux

**Comment by aa2006** [comment]
Recursive cloning does not solve the problem. I ran into the same issue, and tried @notbluu 's solution, then ran it again. Each time, it gives me an error for another file, and i have to wget again... (its annoying)

**Comment by aa2006** [comment]
buuuut in the end it says could not verify integrity of possible corrupted file ...

**Comment by aa2006** [comment]
It works now for some reason :/
