### ISSUE TITLE
More platforms?

### ISSUE THREAD

**Issue by guest123guest** [MandelbrotOS/MandelbrotOS#60]
Would it be possible to support Architectures like PowerPC, or even i386?

**Comment by DamieFC** [comment]
There used to be i386 support, but a rewrite got rid of it 😧

**Comment by segfaultdev** [comment]
Well I really doubt it seeing the highly arch-dependant codebase but maybe if you insist Cayden enough it may work (:

**Comment by 1Wyatt1** [comment]
> Would it be possible to support Architectures like PowerPC, or even i386?
Who the fuck uses PowerPC anymore

**Comment by notbluu** [comment]
I'd highly doubt other platforms would be added for some reasons (including, but not limited to):

- This is a hobbyist OS currently with no mainstream support
- Nobody uses the i386 or PowerPC architectures (besides PowerPC on *some* embedded devices
- Why...??

**Comment by DamieFC** [comment]
> I'd highly doubt other platforms would be added for some reasons (including, but not limited to):
> 
> * This is a hobbyist OS currently with no mainstream support
> * Nobody uses the i386 or PowerPC architectures (besides PowerPC on _some_ embedded devices
> * Why...??

True

**Comment by CaydendW** [comment]
Well, powerpc is dead so no. I doubt I'll add any more arches because this is a lot of work. It could be added later as the src/arch folder does exist. But it won't happen any time soon.

**Comment by segfaultdev** [comment]
> I'd highly doubt other platforms would be added for some reasons (including, but not limited to):
> 
> - This is a hobbyist OS currently with no mainstream support
> - Nobody uses the i386 or PowerPC architectures (besides PowerPC on *some* embedded devices
> - Why...??

LONG LIVE POWER PC
