### ISSUE TITLE
Keyboard drivers incomplete

### ISSUE THREAD

**Issue by aa2006** [MandelbrotOS/MandelbrotOS#63]
The keyboard drivers are missing some features such as special keys handling and \*deep breath\* init.

**Comment by CaydendW** [comment]
Bruh that is your job.
Go do it

**Comment by aa2006** [comment]
> Bruh that is your job.
> Go do it

dude i posted the issue here so it stays on my gh home page so i remember to do it

**Comment by aa2006** [comment]
ok so #66 is gonna solve dis so yay so i can close it when its done merging so yay again
