### ISSUE TITLE
CPU 0: Page Fault at ffffffff80208fa6

### ISSUE THREAD

**Issue by anukranan** [MandelbrotOS/MandelbrotOS#72]
> [ OKAY ] Framebuffer initialized
> [ OKAY ] ACPI initialized
> [ INFO ]  Brought up CPU #0
> [ OKAY ] SMP initialized
>
> CPU 0: Page Fault at ffffffff80208fa6

I have all of the required tools mentioned in the README file, have built the toolchain (I'm on a 64 bit system so I used `make toolchain`), and have run it through Make.

What could be causing this? Thanks!

**Comment by CaydendW** [comment]
I am currently working on stuff so I kinda don't doubt it's broken. You sure you're on the latest commit?

**Comment by anukranan** [comment]
I cloned the master branch with recursed submodules. Is there a newer one?

**Comment by CaydendW** [comment]
Ohhhhh. I know what’s wrong. I changed a thing and forgot to push it. I’m working on a new thing and I forgot to push the change. If you want, I can quickly tell you how to fix it or you can just wait a little and I’ll send up my fixes and features in a week or 2, depending on how long it takes for me to finish debugging and writing

**Comment by anukranan** [comment]
I can wait, and thank you. I assume you will close the issue once that change is pushed, so I'll leave it open yes?

**Comment by CaydendW** [comment]
That's OK. Thanks for the issue :)

**Comment by CaydendW** [comment]
I fixed the issue and added the SATA driver I was working on. You can now build and run it perfectly (I hope) :).
