### ISSUE TITLE
git branch s/master/main/

### ISSUE THREAD

**Issue by devenblake** [MandelbrotOS/MandelbrotOS#77]
A lot of repositories use `main` instead of `master` as the name of the primary branch. The reasoning behind a lot of this is political and uselessly controversial but it may be worth considering following what is current practice and saving a couple characters when typing.

**Comment by Abb1x** [comment]
No

**Comment by Abb1x** [comment]
git has always used master. Why change it?

**Comment by segfaultdev** [comment]
> A lot of repositories use `main` instead of `master` as the name of the primary branch. The reasoning behind a lot of this is political and uselessly controversial but it may be worth considering following what is current practice and saving a couple characters when typing.

I kinda agree with you, though I think most people are switching to `main` because GitHub is actively trying to make it the default. Still, I would personally keep it as is and not care that much about branch names.

**Comment by CaydendW** [comment]
Why would I change it? I selectively chose "master" as it was the default since, forever. There isn't a reason to change it

**Comment by CaydendW** [comment]
Ok this is stale. Closing
